/**
 * @fileoverview Renders `tests/corpus/ATTRIBUTION.md` from every fixture's
 * `meta.json`. `scripts/corpus-add.ts` writes it; the meta suite fails when the
 * committed file differs from what the current fixtures render.
 * @module tests/corpus/attribution
 */
import { join } from 'node:path';
import { CORPUS_DIR, type FixtureMeta } from './fixtures.js';
import type { PubmedFixtureMeta } from './pubmed-fixtures.js';

export const ATTRIBUTION_PATH = join(CORPUS_DIR, 'ATTRIBUTION.md');

const cell = (value: string) =>
  value.replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', ' ');

const byId = <T extends { id: string }>(metas: readonly T[]) =>
  [...metas].sort((a, b) => a.id.localeCompare(b.id));

/**
 * The attribution file for these fixtures: PMC fixtures, then PubMed records, each
 * in fixture-ID order. A PubMed record's license row names the PMC copy that states
 * it.
 */
export function renderAttribution(
  metas: readonly FixtureMeta[],
  pubmedMetas: readonly PubmedFixtureMeta[] = [],
): string {
  const rows = [
    ...byId(metas).map(
      (m) =>
        `| \`pmc/${m.id}\` | ${cell(m.attribution)} | [${m.license.id}](${m.license.url}) | <${m.url}> |`,
    ),
    ...byId(pubmedMetas).map(
      (m) =>
        `| \`pubmed/${m.id}\` | ${cell(m.attribution)} | [${m.license.id}](${m.license.url}), stated by [${m.identifiers.pmcid}](${m.license.source}) | <${m.url}> |`,
    ),
  ];
  return [
    '# Corpus attribution',
    '',
    "Generated by `scripts/corpus-add.ts` from each fixture's `meta.json`. Do not edit by hand.",
    '',
    "Every document under `tests/corpus/fixtures/` is the work of its authors, redistributed here unmodified under the license listed. This project's license does not apply to them.",
    '',
    ...(rows.length === 0
      ? ['No fixtures yet.']
      : ['| Fixture | Work | License | Source |', '|:---|:---|:---|:---|', ...rows]),
    '',
  ].join('\n');
}
